# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8387f5d77263c4a41cf57df11cc4f386"
name = "Build Your Box app"
handle = "build-your-box-app-1"
application_url = "https://foto-downloads-largely-penalties.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-bac0fc57.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://foto-downloads-largely-penalties.trycloudflare.com/auth/callback",
  "https://foto-downloads-largely-penalties.trycloudflare.com/auth/shopify/callback",
  "https://foto-downloads-largely-penalties.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
